[package]
name = "cow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
dotenv = "0.15.0"
tokio = { version = "1.5.0", features = ["net", "rt", "sync", "macros", "rt-multi-thread"] }
log = "0.4"
env_logger = "0.9.0"